import type { Metadata } from "next";
import { Geist_Mono, IBM_Plex_Sans, Space_Grotesk } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

// PHI (humanist) — headings, nav, body. Matches the brand guide's example.
const phi = IBM_Plex_Sans({
  variable: "--font-phi",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// IOTA (geometric) — numbers, metrics, technical labels.
const iota = Space_Grotesk({
  variable: "--font-iota",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IPHIPI Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${phi.variable} ${iota.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
